set_property IOSTANDARD LVCMOS33 [get_ports {EL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {EL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {NL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {WL[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {WL[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {WL[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN E3 [get_ports clk]

set_property PACKAGE_PIN V11 [get_ports {NL[2]}]
set_property PACKAGE_PIN V12 [get_ports {NL[1]}]
set_property PACKAGE_PIN V14 [get_ports {NL[0]}]
set_property PACKAGE_PIN V15 [get_ports {SL[2]}]
set_property PACKAGE_PIN T16 [get_ports {SL[1]}]
set_property PACKAGE_PIN U14 [get_ports {SL[0]}]
set_property PACKAGE_PIN T15 [get_ports {EL[2]}]
set_property PACKAGE_PIN V16 [get_ports {EL[1]}]
set_property PACKAGE_PIN U16 [get_ports {EL[0]}]
set_property PACKAGE_PIN U17 [get_ports {WL[2]}]
set_property PACKAGE_PIN V17 [get_ports {WL[1]}]
set_property PACKAGE_PIN R18 [get_ports {WL[0]}]
set_property PACKAGE_PIN P18 [get_ports reset]

#create_clock -period 10.000 -name clk -waveform {0.000 5.000} -add
